name: Build Unraid Plugin

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build Raidman
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache-dependency-path: go.sum

      - name: Build
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          go mod download
          go build -v -o raidman src/cmd/app/main.go

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: raidman-binary
          path: raidman
          if-no-files-found: error

      - name: Commit and Push Binary
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add raidman
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update raidman binary [skip ci]"
            git push
          fi
